CREATE OR REPLACE TRIGGER ACCOUNT_PROFILE_T_BUID_TRG
BEFORE INSERT OR UPDATE OR DELETE
ON PIN.ACCOUNT_PROFILE_T
BEGIN
    IF NOT PK91_ACCOUNT_PROFILE_TG.latch THEN
      PK91_ACCOUNT_PROFILE_TG.clear_tbls;
    END IF;
EXCEPTION
   WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END;
/
