CREATE OR REPLACE TRIGGER COMPANY_T_BI_TRG
BEFORE INSERT
ON PIN.COMPANY_T
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
    -- проставляем id компании
    IF :NEW.COMPANY_ID IS NULL THEN 
       :NEW.COMPANY_ID := SQ_CLIENT_ID.NEXTVAL;
    END IF;  
EXCEPTION
   WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ACCOUNT_PROFILE_T_BIU_TRG;
/
