CREATE OR REPLACE TRIGGER PAYMENT_T_BIU_TRG
BEFORE INSERT OR UPDATE
ON PIN.PAYMENT_T
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
    IF INSERTING THEN
      :NEW.CREATE_DATE := SYSDATE;
      :NEW.LAST_MODIFIED := SYSDATE;
    ELSIF UPDATING THEN  
      :NEW.LAST_MODIFIED := SYSDATE;
    END IF;
EXCEPTION
   WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ORDER_BODY_T_BIU_TRG;
/
