CREATE OR REPLACE TRIGGER ACCOUNT_PROFILE_T_AUID_TRG
AFTER INSERT OR UPDATE OR DELETE
ON PIN.ACCOUNT_PROFILE_T
BEGIN
    IF NOT PK91_ACCOUNT_PROFILE_TG.latch THEN
      PK91_ACCOUNT_PROFILE_TG.update_profile_t;
    END IF;
EXCEPTION
   WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END;
/
